#cloud-config
autoinstall:
  version: 1


  locale: es_ES.UTF-8
  keyboard:
    layout: es
  timezone: Europe/Rome

  network:
    version: 2
    ethernets:
      enp1s0:
        dhcp4: true

  identity:
    username: usuario
    hostname: linuxconfig
    password: '$6$rounds=4096$xxxxxxxxxxxxxx'

  packages:
    - git
    - python3-pip


  shutdown: reboot
